name: Build Youssef APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Disable Flutter Analytics
        run: |
          flutter config --no-analytics

      - name: Install Dependencies
        run: |
          pip install flet yt-dlp
          
      - name: Build APK with Flet
        run: |
          flet build apk --no-android-studio-check

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Youssef-Downloader-APK
          path: build/apk/*.apk
